### ISSUE TITLE
Timbot panics when running `show webopoly standings` with a non-existent users table

### ISSUE THREAD

**Issue by timflannagan** [Daniel-Pivonka/timbot#90]
When attempting to ask timbot to show the current webopoly standings with an empty, but running MySQL database instance locally, the following stack trace is produced:

```bash
$ flannag@localhost timbot [master]  ./scripts/run-timbot-dev.sh 
Established a connection to the MYSQL database instance
Traceback (most recent call last):
  File "./src/timbot.py", line 187, in <module>
    main()
  File "./src/timbot.py", line 161, in main
    run_timbot()
  File "./src/timbot.py", line 156, in run_timbot
    handle_timbot_message(message.replace(timbot_user_id, ''))
  File "./src/timbot.py", line 106, in handle_timbot_message
    raw_standings = db.get_webopoly_standings(conn)
  File "/src/database.py", line 3, in get_webopoly_standings
    cursor.execute('SELECT users.name, webopoly.wins FROM users, webopoly WHERE users.uid = webopoly.uid ORDER BY wins DESC')
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python2.7/site-packages/mysql/connector/connection_cext.py", line 492, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'timbot.users' doesn't exist
```

We should probably ensure that the users database tables exists before attempting to query for that store, or handle any potential errors around that call site better.

**Comment by nathan-weinberg** [comment]
Alternatively, we can just introduce an exception handing for this timbot command so that it prints an error message to slack
